/* eslint-disable */
import type { FeatureBit, Op } from '../lightning';

/** UpdateAction is used to determine the kind of action we are referring to. */
export enum UpdateAction {
    /** ADD - ADD indicates this is an "insertion" kind of action. */
    ADD = 'ADD',
    /** REMOVE - REMOVE indicates this is a "deletion" kind of action. */
    REMOVE = 'REMOVE',
    UNRECOGNIZED = 'UNRECOGNIZED'
}

export enum FeatureSet {
    /**
     * SET_INIT - SET_INIT identifies features that should be sent in an Init message to
     * a remote peer.
     */
    SET_INIT = 'SET_INIT',
    /**
     * SET_LEGACY_GLOBAL - SET_LEGACY_GLOBAL identifies features that should be set in the legacy
     * GlobalFeatures field of an Init message, which maintains backwards
     * compatibility with nodes that haven't implemented flat features.
     */
    SET_LEGACY_GLOBAL = 'SET_LEGACY_GLOBAL',
    /**
     * SET_NODE_ANN - SET_NODE_ANN identifies features that should be advertised on node
     * announcements.
     */
    SET_NODE_ANN = 'SET_NODE_ANN',
    /**
     * SET_INVOICE - SET_INVOICE identifies features that should be advertised on invoices
     * generated by the daemon.
     */
    SET_INVOICE = 'SET_INVOICE',
    /**
     * SET_INVOICE_AMP - SET_INVOICE_AMP identifies the features that should be advertised on
     * AMP invoices generated by the daemon.
     */
    SET_INVOICE_AMP = 'SET_INVOICE_AMP',
    UNRECOGNIZED = 'UNRECOGNIZED'
}

export interface UpdateAddressAction {
    /** Determines the kind of action. */
    action: UpdateAction;
    /** The address used to apply the update action. */
    address: string;
}

export interface UpdateFeatureAction {
    /** Determines the kind of action. */
    action: UpdateAction;
    /** The feature bit used to apply the update action. */
    featureBit: FeatureBit;
}

export interface NodeAnnouncementUpdateRequest {
    /** Set of changes for the features that the node supports. */
    featureUpdates: UpdateFeatureAction[];
    /** Color is the node's color in hex code format. */
    color: string;
    /** Alias or nick name of the node. */
    alias: string;
    /** Set of changes for the node's known addresses. */
    addressUpdates: UpdateAddressAction[];
}

export interface NodeAnnouncementUpdateResponse {
    ops: Op[];
}

/**
 * Peers is a service that can be used to get information and interact
 * with the other nodes of the network.
 */
export interface Peers {
    /**
     * lncli: peers updatenodeannouncement
     * UpdateNodeAnnouncement allows the caller to update the node parameters
     * and broadcasts a new version of the node announcement to its peers.
     */
    updateNodeAnnouncement(
        request?: DeepPartial<NodeAnnouncementUpdateRequest>
    ): Promise<NodeAnnouncementUpdateResponse>;
}

type Builtin =
    | Date
    | Function
    | Uint8Array
    | string
    | number
    | boolean
    | undefined;

type DeepPartial<T> = T extends Builtin
    ? T
    : T extends Array<infer U>
    ? Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
    ? ReadonlyArray<DeepPartial<U>>
    : T extends {}
    ? { [K in keyof T]?: DeepPartial<T[K]> }
    : Partial<T>;
