require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, min_ios_version_supported
prepare_react_native_project!

target 'zeus' do
  config = use_native_modules!


  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # proto
  pod 'SwiftProtobuf', '~> 1.0'

  # use_unimodules!(modules_paths: ['../node_modules'])

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'react-native-blob-util', :path => '../node_modules/react-native-blob-util'

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # Fix fmt consteval errors with Apple Clang 21+ (Xcode 26+)
    Dir.glob(File.join(installer.sandbox.root, '**/fmt/base.h')).each do |base_h|
      next if File.symlink?(base_h)
      content = File.read(base_h)
      unless content.include?('FMT_CONSTEVAL_APPLE_CLANG_WORKAROUND')
        content.gsub!(
          '#elif defined(__apple_build_version__) && __apple_build_version__ < 14000029L',
          "#elif defined(__apple_build_version__) // FMT_CONSTEVAL_APPLE_CLANG_WORKAROUND"
        )
        File.chmod(0644, base_h)
        File.write(base_h, content)
      end
    end

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Disable arm64 builds for the simulator
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      end
    end
  end
end
