// LnurlPayUtils.ts
import url from 'url';
import BigNumber from 'bignumber.js';
import { sha256 } from '@noble/hashes/sha256';

import Base64Utils from './Base64Utils';
import Bolt11Utils from './Bolt11Utils';

export interface LnurlCheckResult {
    ok: boolean;
    reason?: string;
}

/**
 * Enforce the LUD-06 binding between a served payRequest and the invoice the
 * wallet is about to pay: the invoice amount MUST equal the amount the user
 * requested, and the invoice's BOLT11 description_hash (h tag), when the
 * invoice carries one, MUST commit to the exact metadata string the user was
 * shown. Without this, a compromised or malicious LNURL service can display
 * one payee identity while the paid invoice commits to something unrelated
 * (LUD-06 bait-and-switch), or invoice any amount it likes.
 *
 * A missing description_hash is accepted: a large share of real-world
 * services omit the h tag entirely, and any ecash-backed lightning address
 * (including ZEUS Pay cashu addresses) serves an invoice generated by the
 * recipient's Cashu mint through a mint quote, which cannot commit to LNURL
 * metadata at all. The amount check still applies unconditionally.
 *
 * The invoice is decoded locally rather than trusting a backend's decode
 * response, so the check is identical across every backend (several omit
 * description_hash / num_msat from their decode output).
 */
export const verifyLnurlPayInvoice = (
    pr: string,
    metadata: string | undefined,
    expectedAmountMsat: BigNumber.Value
): LnurlCheckResult => {
    let decoded;
    try {
        decoded = Bolt11Utils.decode(pr);
    } catch (err: any) {
        return { ok: false, reason: `undecodable invoice: ${err?.message}` };
    }

    const expected = new BigNumber(expectedAmountMsat);
    if (
        !expected.isFinite() ||
        !new BigNumber(decoded.num_msat).isEqualTo(expected)
    ) {
        return {
            ok: false,
            reason: `invoice amount mismatch: ${
                decoded.num_msat
            } msat !== ${expected.toString()} msat`
        };
    }

    const expectedDescriptionHash =
        typeof metadata === 'string'
            ? Base64Utils.bytesToHex(
                  Array.from(sha256(Base64Utils.utf8ToBytes(metadata)))
              )
            : null;
    if (
        decoded.description_hash &&
        decoded.description_hash !== expectedDescriptionHash
    ) {
        return { ok: false, reason: 'description hash mismatch' };
    }

    return { ok: true };
};

/**
 * Parse an IPv4 literal the way inet_aton does: 1 to 4 dot-separated parts,
 * each decimal, octal (leading 0), or hex (0x), with the final part filling
 * the remaining bytes. Platform resolvers dial hosts like "2130706433",
 * "0177.0.0.1", "0x7f.0.0.1", and "127.1" as loopback, so the private-range
 * check must see the same address the socket will. Returns the four octets,
 * or null when the host is not an IPv4 literal.
 */
const parseIPv4Literal = (host: string): number[] | null => {
    if (!host) return null;
    const parts = host.split('.');
    if (parts.length > 4) return null;
    const values: number[] = [];
    for (const part of parts) {
        let value: number;
        if (/^0x[0-9a-f]+$/i.test(part)) value = parseInt(part, 16);
        else if (/^0[0-7]*$/.test(part)) value = parseInt(part, 8);
        else if (/^[1-9][0-9]*$/.test(part)) value = parseInt(part, 10);
        else return null;
        values.push(value);
    }
    const last = values[values.length - 1];
    const prefix = values.slice(0, -1);
    if (prefix.some((v) => v > 255)) return null;
    const lastBytes = 4 - prefix.length;
    if (last >= Math.pow(256, lastBytes)) return null;
    const octets = [...prefix];
    for (let i = lastBytes - 1; i >= 0; i--) {
        octets.push(Math.floor(last / Math.pow(256, i)) % 256);
    }
    return octets;
};

const isPrivateIPv4 = (host: string): boolean => {
    const octets = parseIPv4Literal(host);
    if (!octets) return false;
    const [a, b] = octets;
    if (a === 0) return true; // "this network"
    if (a === 10) return true; // RFC1918
    if (a === 127) return true; // loopback
    if (a === 169 && b === 254) return true; // link-local + cloud metadata
    if (a === 172 && b >= 16 && b <= 31) return true; // RFC1918
    if (a === 192 && b === 168) return true; // RFC1918
    if (a === 100 && b >= 64 && b <= 127) return true; // CGNAT (RFC6598)
    return false;
};

/**
 * Expand an IPv6 literal into its eight 16-bit groups, handling brackets,
 * zone IDs, "::" compression, and an embedded dotted-quad tail, so that
 * long-form loopback ("[0:0:0:0:0:0:0:1]") and hex-mapped IPv4
 * ("[::ffff:7f00:1]") classify the same as their canonical spellings.
 * Returns null when the host is not a valid IPv6 literal.
 */
const parseIPv6Literal = (host: string): number[] | null => {
    let h = host;
    if (h.startsWith('[') && h.endsWith(']')) h = h.slice(1, -1);
    const zone = h.indexOf('%');
    if (zone !== -1) h = h.slice(0, zone);
    if (h.indexOf(':') === -1) return null;
    const halves = h.split('::');
    if (halves.length > 2) return null;
    const parseGroups = (
        side: string,
        allowV4Tail: boolean
    ): number[] | null => {
        if (side === '') return [];
        const parts = side.split(':');
        const groups: number[] = [];
        for (let i = 0; i < parts.length; i++) {
            const part = parts[i];
            const isLast = i === parts.length - 1;
            if (allowV4Tail && isLast && part.indexOf('.') !== -1) {
                // the embedded IPv4 tail must be a plain dotted quad
                const m = part.match(
                    /^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})$/
                );
                if (!m) return null;
                const octets = m.slice(1).map(Number);
                if (octets.some((o) => o > 255)) return null;
                groups.push(
                    (octets[0] << 8) | octets[1],
                    (octets[2] << 8) | octets[3]
                );
            } else {
                if (!/^[0-9a-f]{1,4}$/i.test(part)) return null;
                groups.push(parseInt(part, 16));
            }
        }
        return groups;
    };
    if (halves.length === 1) {
        const groups = parseGroups(h, true);
        return groups && groups.length === 8 ? groups : null;
    }
    const left = parseGroups(halves[0], false);
    const right = parseGroups(halves[1], true);
    if (left === null || right === null) return null;
    const missing = 8 - left.length - right.length;
    if (missing < 1) return null;
    return [...left, ...new Array(missing).fill(0), ...right];
};

const isPrivateIPv6 = (host: string): boolean => {
    const groups = parseIPv6Literal(host);
    if (!groups) return false;
    // loopback (::1) and unspecified (::)
    if (groups.slice(0, 7).every((g) => g === 0) && groups[7] <= 1) {
        return true;
    }
    // IPv4-mapped (::ffff:a.b.c.d, however spelled) and the deprecated
    // IPv4-compatible ::a.b.c.d form classify as the embedded IPv4 address
    if (
        groups.slice(0, 5).every((g) => g === 0) &&
        (groups[5] === 0xffff || groups[5] === 0)
    ) {
        const v4 = [
            groups[6] >> 8,
            groups[6] & 0xff,
            groups[7] >> 8,
            groups[7] & 0xff
        ].join('.');
        return isPrivateIPv4(v4);
    }
    if ((groups[0] & 0xfe00) === 0xfc00) return true; // fc00::/7 unique-local
    if ((groups[0] & 0xffc0) === 0xfe80) return true; // fe80::/10 link-local
    return false;
};

const isPrivateOrReservedHost = (hostnameRaw: string): boolean => {
    // a trailing dot is the root-anchored form of the same name
    let hostname = hostnameRaw;
    while (hostname.endsWith('.')) hostname = hostname.slice(0, -1);
    if (hostname === 'localhost' || hostname.endsWith('.localhost')) {
        return true;
    }
    return isPrivateIPv4(hostname) || isPrivateIPv6(hostname);
};

/**
 * Reject a service-supplied LNURL callback that the wallet must not fetch:
 *  - cleartext http to a non-onion host (leaks the amount/comment and lets a
 *    network attacker substitute the invoice), and
 *  - any request aimed at loopback / private / link-local infrastructure
 *    (SSRF-by-callback, e.g. the 169.254.169.254 cloud-metadata endpoint).
 *
 * A cross-domain https host is permitted (some services front the callback on a
 * separate CDN host). This blocks IP-literal SSRF targets only; a hostname that
 * resolves to an internal address (DNS rebinding) is out of scope here.
 */
export const isLnurlCallbackAllowed = (callback: string): LnurlCheckResult => {
    if (typeof callback !== 'string' || callback.length === 0) {
        return { ok: false, reason: 'missing callback URL' };
    }

    let parsed;
    try {
        parsed = url.parse(callback);
    } catch (err: any) {
        return { ok: false, reason: 'unparseable callback URL' };
    }

    const protocol = (parsed.protocol || '').toLowerCase();
    const hostname = (parsed.hostname || '').toLowerCase();
    if (!hostname) {
        return { ok: false, reason: 'callback URL has no host' };
    }

    const isOnion = hostname.endsWith('.onion');
    if (protocol !== 'https:' && !(protocol === 'http:' && isOnion)) {
        return {
            ok: false,
            reason: 'callback must use https (http allowed only for .onion)'
        };
    }

    if (isPrivateOrReservedHost(hostname)) {
        return {
            ok: false,
            reason: 'callback targets a private or reserved address'
        };
    }

    return { ok: true };
};
